// Category definitions with blocks for the block palette
export const BLOCK_CATEGORIES = [
  {
    id: 'events',
    name: 'Events',
    colour: '#FFAB19',
    icon: '🏁',
    blocks: [
      'event_game_start',
      'event_key_pressed',
      'event_clicked',
      'event_forever',
      'event_when_receive',
      'event_when_touching',
      'event_when_clone_start',
    ],
  },
  {
    id: 'motion',
    name: 'Motion',
    colour: '#4C97FF',
    icon: '➡️',
    blocks: [
      'motion_move_steps',
      'motion_go_to',
      'motion_change_x',
      'motion_change_y',
      'motion_set_x',
      'motion_set_y',
      'motion_point_direction',
      'motion_point_towards',
    ],
  },
  {
    id: 'looks',
    name: 'Looks',
    colour: '#9966FF',
    icon: '👁️',
    blocks: [
      'looks_show',
      'looks_hide',
      'looks_set_size',
      'looks_change_size',
      'looks_set_opacity',
      'looks_go_to_front',
      'looks_go_to_back',
    ],
  },
  {
    id: 'physics',
    name: 'Physics',
    colour: '#40BF4A',
    icon: '⚡',
    blocks: [
      'physics_enable',
      'physics_set_velocity',
      'physics_set_velocity_x',
      'physics_set_velocity_y',
      'physics_set_gravity',
      'physics_set_bounce',
      'physics_collide_bounds',
      'physics_immovable',
    ],
  },
  {
    id: 'control',
    name: 'Control',
    colour: '#FFBF00',
    icon: '🔄',
    blocks: [
      'control_wait',
      'control_repeat',
      'controls_if',
      'control_stop',
      'control_switch_scene',
      'control_clone',
      'control_delete_clone',
      'control_broadcast',
      'control_broadcast_wait',
    ],
  },
  {
    id: 'sensing',
    name: 'Sensing',
    colour: '#5CB1D6',
    icon: '👆',
    blocks: [
      'sensing_key_pressed',
      'sensing_mouse_down',
      'sensing_mouse_x',
      'sensing_mouse_y',
      'sensing_touching',
      'sensing_distance_to',
    ],
  },
  {
    id: 'camera',
    name: 'Camera',
    colour: '#0fBDA8',
    icon: '📷',
    blocks: [
      'camera_follow_me',
      'camera_follow_object',
      'camera_stop_follow',
      'camera_go_to',
      'camera_shake',
      'camera_zoom',
      'camera_fade',
    ],
  },
  {
    id: 'sound',
    name: 'Sound',
    colour: '#CF63CF',
    icon: '🔊',
    blocks: [
      'sound_play',
      'sound_play_until_done',
      'sound_stop_all',
      'sound_set_volume',
      'sound_change_volume',
    ],
  },
  {
    id: 'operators',
    name: 'Operators',
    colour: '#59C059',
    icon: '➕',
    blocks: [
      'math_number',
      'math_arithmetic',
      'math_random_int',
      'logic_compare',
      'logic_operation',
      'logic_negate',
    ],
  },
  {
    id: 'variables',
    name: 'Variables',
    colour: '#FF8C1A',
    icon: '📦',
    blocks: ['variables_get', 'variables_set', 'math_change'],
    isVariables: true,
  },
];
